from enum import StrEnum


class Legend(StrEnum):
    ASH = 'Ash'
    ALTER = 'Alter'
    BALLISTIC = 'Ballistic'
    BANGALORE = 'Bangalore'
    BLOODHOUND = 'Bloodhound'
    CAUSTIC = 'Caustic'
    CATALYST = 'Catalyst'
    CONDUIT = 'Conduit'
    CRYPTO = 'Crypto'
    FUSE = 'Fuse'
    GIBRALTAR = 'Gibraltar'
    HORIZON = 'Horizon'
    LIFELINE = 'Lifeline'
    LOBA = 'Loba'
    MAD_MAGGIE = 'Mad Maggie'
    MIRAGE = 'Mirage'
    NEWCASTLE = 'Newcastle'
    OCTANE = 'Octane'
    PATHFINDER = 'Pathfinder'
    RAMPART = 'Rampart'
    REVENANT = 'Revenant'
    SEER = 'Seer'
    VALKYRIE = 'Valkyrie'
    VANTAGE = 'Vantage'
    WATTSON = 'Wattson'
    WRAITH = 'Wraith'

